ALTER TABLE "email_send_runs"
    ALTER COLUMN "completedAt" SET DATA TYPE TIMESTAMP USING "completedAt"::TIMESTAMP,

    ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP USING "createdAt"::TIMESTAMP,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
      ALTER COLUMN "startedAt" SET DATA TYPE TIMESTAMP USING "startedAt"::TIMESTAMP,
ALTER COLUMN "startedAt" SET DEFAULT CURRENT_TIMESTAMP,

    ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP USING "updatedAt"::TIMESTAMP;
