-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "AuditAction" ADD VALUE 'VENDOR_INVOICE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'VENDOR_INVOICE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'VENDOR_INVOICE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'HARDWARE_PURCHASE_INVOICE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'HARDWARE_PURCHASE_INVOICE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'HARDWARE_PURCHASE_INVOICE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'FRANCHISE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'FRANCHISE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'FRANCHISE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'CUSTOMER_REQUEST_SUBMITTED';
ALTER TYPE "AuditAction" ADD VALUE 'CUSTOMER_REQUEST_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE 'CUSTOMER_REQUEST_REJECTED';
ALTER TYPE "AuditAction" ADD VALUE 'CUSTOMER_REQUEST_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'GROUP_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'GROUP_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'GROUP_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'GROUP_SUBACCOUNT_ADDED';
ALTER TYPE "AuditAction" ADD VALUE 'GROUP_SUBACCOUNT_REMOVED';
ALTER TYPE "AuditAction" ADD VALUE 'MINER_REPAIR_NOTE_ADDED';
ALTER TYPE "AuditAction" ADD VALUE 'MINER_REPAIR_NOTE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'MINER_REPAIR_NOTE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'MINER_OWNERSHIP_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'MINER_POOL_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'MINER_HASHRATE_BENCHMARK_SET';
ALTER TYPE "AuditAction" ADD VALUE 'HARDWARE_PROCUREMENT_RECORDED';
ALTER TYPE "AuditAction" ADD VALUE 'MINER_HASHRATE_ALERT_ACKNOWLEDGED';
ALTER TYPE "AuditAction" ADD VALUE 'MINER_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'MINER_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'MINER_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'HARDWARE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'HARDWARE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'HARDWARE_DELETED';

-- AlterTable
ALTER TABLE "hardware" ADD COLUMN     "createdById" TEXT,
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "deletedById" TEXT,
ADD COLUMN     "updatedById" TEXT;

-- AlterTable
ALTER TABLE "miners" ADD COLUMN     "createdById" TEXT,
ADD COLUMN     "deletedAt" TIMESTAMP(3),
ADD COLUMN     "deletedById" TEXT,
ADD COLUMN     "updatedById" TEXT;

-- AddForeignKey
ALTER TABLE "hardware" ADD CONSTRAINT "hardware_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "hardware" ADD CONSTRAINT "hardware_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "hardware" ADD CONSTRAINT "hardware_deletedById_fkey" FOREIGN KEY ("deletedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "miners" ADD CONSTRAINT "miners_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "miners" ADD CONSTRAINT "miners_updatedById_fkey" FOREIGN KEY ("updatedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "miners" ADD CONSTRAINT "miners_deletedById_fkey" FOREIGN KEY ("deletedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
