ALTER TABLE "payback_config"

ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP USING "createdAt"::TIMESTAMP,
    ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,

    ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP USING "updatedAt"::TIMESTAMP;
